### ISSUE TITLE
need your suggestion

### ISSUE THREAD

**Issue by zangetsudo** [Taketsuru/khttpd#3]
hi, Taketsuru.
great job, well done. i have not seen any project like this.

i want to port your project to Linux. need your suggestion on how to make it happen smoothly with out re-write all the code since i m new  here ^_^.

i also want to ask if there is any simple solution on client's side java script to ajax the info from server side.
i saw you used AngularJS here, but it seems require much more java script, list here:
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')

thanks.

**Comment by Taketsuru** [comment]
Thank you, Zangetsudo.

The client side is in very early stage of the development.  I don't think porting now is good idea.
The missing javascript files are parts of Bootstrap.

**Comment by zangetsudo** [comment]
ok. Taketsuru
i'm now worrying about loop and ajax the server side data like sysctl and insert each item in the items.
i found there maybe a solution in http://stackoverflow.com/questions/16460326/how-to-run-angularjs-ajax-request-in-loop-but-with-delay. but i_m pretty new to javascript and now im going to struggle with the code.

help you can drop some ideas.

**Comment by Taketsuru** [comment]
Send a request in a loop for each data like sysctl is not efficient.  I think improving the web API so that multiple items can be retrieved by sending single request is much better.

**Comment by zangetsudo** [comment]
yes. i_m just improving the web API now.
this is what i_m going to do:
when the user mark the CPU usage in real time(of-course in web api), the web-API will get the data in loop from sysctl each time(like 5 seconds interval) and insert it in to the tab or something that we can see.
this is going to like what we do in terminal of command top -d 5.
what do you see ?
